def on_button_pressed_a():
    music.play_melody("- - - - - - - - ", 40)
    music.play_tone(466, music.beat(BeatFraction.QUARTER))
    music.play_tone(466, music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(466, music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(622, music.beat(BeatFraction.EIGHTH))
    music.play_tone(698, music.beat(BeatFraction.EIGHTH))
    music.play_tone(622, music.beat(BeatFraction.EIGHTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(622, music.beat(BeatFraction.EIGHTH))
    music.play_tone(698, music.beat(BeatFraction.EIGHTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(622, music.beat(BeatFraction.EIGHTH))
    music.play_tone(466, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(415, music.beat(BeatFraction.HALF))
    music.play_tone(415, music.beat(BeatFraction.EIGHTH))
    music.rest(music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
input.on_button_pressed(Button.A, on_button_pressed_a)

music.set_volume(183)